# radar-visualization robot-side env
export ROS_DOMAIN_ID={{ROS_DOMAIN_ID}}
export RMW_IMPLEMENTATION={{RMW_IMPLEMENTATION}}
export ROS_DISCOVERY_SERVER={{ROS_DISCOVERY_SERVER}}
export ROS_SUPER_CLIENT={{ROS_SUPER_CLIENT}}
export FASTDDS_BUILTIN_TRANSPORTS={{FASTDDS_BUILTIN_TRANSPORTS}}
