# radar-visualization robot-side env
# 不加 export 前缀：systemd EnvironmentFile 与 start_rosbridge.sh 的 `set -a; source` 都能正确加载
ROS_DOMAIN_ID={{ROS_DOMAIN_ID}}
RMW_IMPLEMENTATION={{RMW_IMPLEMENTATION}}
ROS_DISCOVERY_SERVER={{ROS_DISCOVERY_SERVER}}
ROS_SUPER_CLIENT={{ROS_SUPER_CLIENT}}
FASTDDS_BUILTIN_TRANSPORTS={{FASTDDS_BUILTIN_TRANSPORTS}}
ROS_LOCALHOST_ONLY={{ROS_LOCALHOST_ONLY}}
FASTRTPS_DEFAULT_PROFILES_FILE={{FASTRTPS_DEFAULT_PROFILES_FILE}}
FASTDDS_DEFAULT_PROFILES_FILE={{FASTDDS_DEFAULT_PROFILES_FILE}}
ROS_LOG_DIR={{ROS_LOG_DIR}}
